# Generated by Django 5.1.5 on 2025-02-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_image_eventregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='gallery_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
