# Generated by Django 5.1.5 on 2025-02-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_donation_date_donation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(blank=True, choices=[('sport', 'Sport'), ('sosial', 'Kegiatan Sosial'), ('pendidikan', 'Pendidikan'), ('hiburan', 'Hiburan'), ('politik', 'Politik'), ('ekonomi', 'Ekonomi'), ('teknologi', 'Teknologi'), ('kesehatan', 'Kesehatan'), ('budaya', 'Budaya'), ('otomotif', 'Otomotif')], max_length=100, null=True),
        ),
    ]
