# Generated by Django 5.1.5 on 2025-02-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(blank=True, choices=[('Sport', 'Sport'), ('Sosial', 'Kegiatan Sosial'), ('Pendidikan', 'Pendidikan'), ('Hiburan', 'Hiburan'), ('Politik', 'Politik'), ('Ekonomi', 'Ekonomi'), ('Teknologi', 'Teknologi'), ('Kesehatan', 'Kesehatan'), ('Budaya', 'Budaya'), ('Otomotif', 'Otomotif')], max_length=100, null=True),
        ),
    ]
