# Generated by Django 5.1.5 on 2025-02-17 13:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_galleryalbum_alter_alumniprofile_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
    ]
