# Generated by Django 5.1.5 on 2025-02-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_requested',
            field=models.BooleanField(default=False),
        ),
    ]
