# Generated by Django 5.1.5 on 2025-02-19 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_user_verification_requested'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategicDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('decision_type', models.CharField(choices=[('event', 'Event Besar'), ('policy', 'Kebijakan')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategic_decisions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
