# Generated by Django 5.1.5 on 2025-02-19 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_strategicdecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategicdecision',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategicdecision',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_strategic_decisions', to=settings.AUTH_USER_MODEL),
        ),
    ]
