# Generated by Django 5.1.5 on 2025-02-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_strategicdecision_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategicdecision',
            name='approval_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
