# Generated by Django 5.1.5 on 2025-02-20 06:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile_photos/profile.png', null=True, upload_to=core.models.RandomFilename('profile_photos')),
        ),
        migrations.AlterField(
            model_name='donation',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to=core.models.RandomFilename('donation_proofs')),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.RandomFilename('event_images')),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to=core.models.RandomFilename('gallery_images')),
        ),
        migrations.AlterField(
            model_name='galleryalbum',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.RandomFilename('gallery_albums')),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to=core.models.RandomFilename('gallery_images')),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.RandomFilename('news_images')),
        ),
    ]
