# Generated by Django 5.1.5 on 2025-02-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_alumniprofile_profile_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(max_length=255)),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Direksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(max_length=255)),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
    ]
